nbp:
  url: https://api.nbp.pl/api
spring:
  application:
    name: Bank account app
  datasource:
    url: jdbc:h2:file:./data/bank-account
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: full
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: TRACE
    pl:
      nn:
        bankaccount:
          infrastructure:
            currency: DEBUG