nbp:
  url: https://api.nbp.pl/api
spring:
  application:
    name: Bank account app
  datasource:
    url: jdbc:h2:mem:bankAccountDb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic