spring:
  application:
    name: Bank account app
  datasource:
    url: jdbc:h2:mem:bankAccountDb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create